### ISSUE TITLE
API for Bot power

### ISSUE THREAD

**Issue by TimSmole** [liagame/lia-SDK#7]
Hi,

first thank you all for organising this challenge, you've done a great job! 

But I have two questions: 
- I am assuming that opponent's current Bot power is intentionally not available during the game (please correct me if I'm wrong). 

- I'm curious if there is (or could it be implemented) an API or CLI command that would return the final result of the game (not only winner of the game, but also Bot powers for both players)?

Thanks in advance!

**Comment by Svigelj** [comment]
Hi @TimSmole !

* ***I am assuming that opponent's current Bot power is intentionally not available during the game (please correct me if I'm wrong).***
That is correct, opponent bot power is intentionally not available through the API to make the game more interesting. You only have the information about the number of units that opponent has. 
-  ***I'm curious if there is (or could it be implemented) an API or CLI command that would return the final result of the game (not only winner of the game, but also Bot powers for both players)?***
It is possible. Replay files hold the data about the whole game and can be parsed to retrieve the needed information. The thing is that they are encoded as protobuf messages so you need to have a library to parse them. If you are interested I can drop you a Python3 example below that retrieves bot powers from the replay file.

**Comment by TimSmole** [comment]
@Svigelj, thanks for quick reply!

I thought so but I didn't know how to read the replay files. So an example would be very appreciated!

**Comment by Svigelj** [comment]
@TimSmole here is a quick example of how to extract the power of both bots at the end of the game.

If there will be enough interest for parsing replay files we will add the support into CLI tool and explain in more details how to use it in our documentation. 

--- 
#### How to use
1. Download [last_game_stats.zip](https://github.com/liagame/lia-SDK/files/2860912/last_game_stats.zip) and unzip it somewhere (eg. into your Lia-SDK folder).
2. Install requirements with pip from `requirements.txt`
3. Run a python3 script `last_game_stats.py` providing it a path to the replay file (eg. `replays/1.lia`).
4. It will print out the lastest state and some other data, check the script to see what is printed.

I hope it helps!

**Comment by TimSmole** [comment]
@Svigelj thanks for the script - it works well for obtaining the final scores. 

I have a few more questions though. 

- Would it be possible to add a callback API for game termination (perhaps providing it the final bot powers)? This would allow for some final post-game cleaning tasks, saving data and so on. My first idea was just to count the number of times the update method was called, but that clearly works only if the game is finished because of the timeout. Second thought was to save the data on every call of update method, but using IO operations 10 per second won't really work well :sweat_smile: So a callback like on_finish(final_stats) would be very useful.

- Second question is regarding the .lia files. I understand this files contain all the necessary data to replay old games, but is the data stored in a similar fashion that is provided in the API (the game_state dictionary)? I would assume not, but I would like to hear your thoughts on how difficult you think it would be to reconstruct the sequence of states and actions for a given file? Also, will the .lia files for tournament games be available at some point during the competition? Otherwise I guess the last question doesn't really matter :wink: 

Thanks for your help!

**Comment by Svigelj** [comment]
@TimSmole sure no problem. Answering the above questions:

* ***Would it be possible to add a callback API for game termination (perhaps providing it the final bot powers)?***
This would be possible but since we can't automatically update players bots on their development environment and the API they use (we can only update the core game-engine in the SDK), some players wouldn't get the change and would thus be in disadvantage. We may add this functionality after the tournament, though.
There is is a way to fairly accurately detect when the game was finished from within your bot. Check [this thread](https://www.reddit.com/r/liagame/comments/as20e1/detecting_final_frame/) for details.
* ***Will the .lia files for tournament games be available at some point during the competition?*** 
You can already download .lia files for all the games played in the tournament. When you watch the game from our Games page, you can see that it has url of something like https://www.liagame.com/games/{game-id}. The last part is the id of the game, using which you can download the .lia file for that game at https://storage.production.cloud1.liagame.com/replays/{game-id}.lia. 
So for example the game at https://www.liagame.com/games/1d248a31-52e2-43f9-b3af-43aead960dfe uses replay file available at https://storage.production.cloud1.liagame.com/replays/1d248a31-52e2-43f9-b3af-43aead960dfe.lia.
* ***How difficult you think it would be to reconstruct the sequence of states and actions for a given file***
To reconstruct the actual states would take some work but is not impossible. But I don't know if it would be possible to fairly accurately reconstruct the actual actions that units took, most likely not... But you can try to store every state in array of states in RAM and print it out to the file just when the game ends. This way you should gain some performance boost and the states are not really big so it should not consume too much of your memory.
* ***How replay files are stored?***
The replay file holds the data with which you can reproduce the movement of all elements in the game. The logic with which we store the data in the .lia files is based of of this [awesome article](https://www.forrestthewoods.com/blog/tech_of_planetary_annihilation_chrono_cam/). If you will want to know more or will want to reconstruct some data, we can get in more details about our implementation. :smiley:
